/**
 * Paleta de Colores Personalizable - 12 Colores Pastel + Gradientes
 */

// Colores base pastel con sus variantes
export const colorPalettes = [
  {
    id: 'rose',
    name: 'Rosa Pastel',
    primary: '#fecdd3',
    primaryLight: '#ffe4e6',
    primaryDark: '#fda4af',
    gradient: 'from-rose-300 to-rose-400',
    gradientDark: 'from-rose-400 to-rose-500',
    bg: 'bg-rose-50',
    bgDark: 'bg-rose-900/20',
    text: 'text-rose-600',
    textDark: 'text-rose-400',
    border: 'border-rose-200',
    borderDark: 'border-rose-800',
  },
  {
    id: 'orange',
    name: 'Naranja Pastel',
    primary: '#fed7aa',
    primaryLight: '#ffedd5',
    primaryDark: '#fdba74',
    gradient: 'from-orange-300 to-orange-400',
    gradientDark: 'from-orange-400 to-orange-500',
    bg: 'bg-orange-50',
    bgDark: 'bg-orange-900/20',
    text: 'text-orange-600',
    textDark: 'text-orange-400',
    border: 'border-orange-200',
    borderDark: 'border-orange-800',
  },
  {
    id: 'amber',
    name: 'Ámbar Pastel',
    primary: '#fde68a',
    primaryLight: '#fef3c7',
    primaryDark: '#fbbf24',
    gradient: 'from-amber-300 to-amber-400',
    gradientDark: 'from-amber-400 to-amber-500',
    bg: 'bg-amber-50',
    bgDark: 'bg-amber-900/20',
    text: 'text-amber-600',
    textDark: 'text-amber-400',
    border: 'border-amber-200',
    borderDark: 'border-amber-800',
  },
  {
    id: 'emerald',
    name: 'Esmeralda Pastel',
    primary: '#a7f3d0',
    primaryLight: '#d1fae5',
    primaryDark: '#34d399',
    gradient: 'from-emerald-300 to-emerald-400',
    gradientDark: 'from-emerald-400 to-emerald-500',
    bg: 'bg-emerald-50',
    bgDark: 'bg-emerald-900/20',
    text: 'text-emerald-600',
    textDark: 'text-emerald-400',
    border: 'border-emerald-200',
    borderDark: 'border-emerald-800',
  },
  {
    id: 'teal',
    name: 'Turquesa Pastel',
    primary: '#99f6e4',
    primaryLight: '#ccfbf1',
    primaryDark: '#2dd4bf',
    gradient: 'from-teal-300 to-teal-400',
    gradientDark: 'from-teal-400 to-teal-500',
    bg: 'bg-teal-50',
    bgDark: 'bg-teal-900/20',
    text: 'text-teal-600',
    textDark: 'text-teal-400',
    border: 'border-teal-200',
    borderDark: 'border-teal-800',
  },
  {
    id: 'sky',
    name: 'Cielo Pastel',
    primary: '#bae6fd',
    primaryLight: '#e0f2fe',
    primaryDark: '#38bdf8',
    gradient: 'from-sky-300 to-sky-400',
    gradientDark: 'from-sky-400 to-sky-500',
    bg: 'bg-sky-50',
    bgDark: 'bg-sky-900/20',
    text: 'text-sky-600',
    textDark: 'text-sky-400',
    border: 'border-sky-200',
    borderDark: 'border-sky-800',
  },
  {
    id: 'blue',
    name: 'Azul Pastel',
    primary: '#bfdbfe',
    primaryLight: '#dbeafe',
    primaryDark: '#60a5fa',
    gradient: 'from-blue-300 to-blue-400',
    gradientDark: 'from-blue-400 to-blue-500',
    bg: 'bg-blue-50',
    bgDark: 'bg-blue-900/20',
    text: 'text-blue-600',
    textDark: 'text-blue-400',
    border: 'border-blue-200',
    borderDark: 'border-blue-800',
  },
  {
    id: 'indigo',
    name: 'Índigo Pastel',
    primary: '#c7d2fe',
    primaryLight: '#e0e7ff',
    primaryDark: '#818cf8',
    gradient: 'from-indigo-300 to-indigo-400',
    gradientDark: 'from-indigo-400 to-indigo-500',
    bg: 'bg-indigo-50',
    bgDark: 'bg-indigo-900/20',
    text: 'text-indigo-600',
    textDark: 'text-indigo-400',
    border: 'border-indigo-200',
    borderDark: 'border-indigo-800',
  },
  {
    id: 'violet',
    name: 'Violeta Pastel',
    primary: '#ddd6fe',
    primaryLight: '#ede9fe',
    primaryDark: '#a78bfa',
    gradient: 'from-violet-300 to-violet-400',
    gradientDark: 'from-violet-400 to-violet-500',
    bg: 'bg-violet-50',
    bgDark: 'bg-violet-900/20',
    text: 'text-violet-600',
    textDark: 'text-violet-400',
    border: 'border-violet-200',
    borderDark: 'border-violet-800',
  },
  {
    id: 'purple',
    name: 'Púrpura Pastel',
    primary: '#e9d5ff',
    primaryLight: '#f3e8ff',
    primaryDark: '#c084fc',
    gradient: 'from-purple-300 to-purple-400',
    gradientDark: 'from-purple-400 to-purple-500',
    bg: 'bg-purple-50',
    bgDark: 'bg-purple-900/20',
    text: 'text-purple-600',
    textDark: 'text-purple-400',
    border: 'border-purple-200',
    borderDark: 'border-purple-800',
  },
  {
    id: 'fuchsia',
    name: 'Fucsia Pastel',
    primary: '#f5d0fe',
    primaryLight: '#fae8ff',
    primaryDark: '#e879f9',
    gradient: 'from-fuchsia-300 to-fuchsia-400',
    gradientDark: 'from-fuchsia-400 to-fuchsia-500',
    bg: 'bg-fuchsia-50',
    bgDark: 'bg-fuchsia-900/20',
    text: 'text-fuchsia-600',
    textDark: 'text-fuchsia-400',
    border: 'border-fuchsia-200',
    borderDark: 'border-fuchsia-800',
  },
  {
    id: 'pink',
    name: 'Rosa Claro Pastel',
    primary: '#fbcfe8',
    primaryLight: '#fce7f3',
    primaryDark: '#f472b6',
    gradient: 'from-pink-300 to-pink-400',
    gradientDark: 'from-pink-400 to-pink-500',
    bg: 'bg-pink-50',
    bgDark: 'bg-pink-900/20',
    text: 'text-pink-600',
    textDark: 'text-pink-400',
    border: 'border-pink-200',
    borderDark: 'border-pink-800',
  },
]

// Gradientes especiales
export const specialGradients = [
  {
    id: 'sunset',
    name: 'Atardecer',
    from: '#fb7185',
    to: '#f59e0b',
    class: 'from-pink-500 to-orange-500',
  },
  {
    id: 'ocean',
    name: 'Océano',
    from: '#06b6d4',
    to: '#3b82f6',
    class: 'from-cyan-500 to-blue-500',
  },
  {
    id: 'forest',
    name: 'Bosque',
    from: '#10b981',
    to: '#84cc16',
    class: 'from-emerald-500 to-lime-500',
  },
  {
    id: 'lavender',
    name: 'Lavanda',
    from: '#a78bfa',
    to: '#f472b6',
    class: 'from-violet-500 to-pink-500',
  },
  {
    id: 'aurora',
    name: 'Aurora',
    from: '#22d3ee',
    to: '#a78bfa',
    class: 'from-cyan-400 to-violet-500',
  },
  {
    id: 'peach',
    name: 'Durazno',
    from: '#fb923c',
    to: '#f472b6',
    class: 'from-orange-400 to-pink-400',
  },
]

// Obtener paleta por ID
export const getPaletteById = (id) => {
  return colorPalettes.find(p => p.id === id) || colorPalettes[6] // Default to blue
}

// Obtener gradiente por ID
export const getGradientById = (id) => {
  return specialGradients.find(g => g.id === id) || specialGradients[1] // Default to ocean
}
